name: CI

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: yarn install
      
    - name: IsEmptyInterface benchmark
      run: |
        yarn diag:IsEmptyInterface
        yarn perf:IsEmptyInterface
